Repository codestates-seb/seb44_main_004, pull requests merged in 2023-07, with the labels that each got.

#21 Init/be entity 엔티티 클래스 초기셋팅
  server/build.gradle
  server/src/main/java/com/seb_main_004/whosbook/curation/category/Category.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/dto/PageInfo.java
  server/src/main/java/com/seb_main_004/whosbook/exception/BusinessLogicException.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/member/Member.java
  server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
  server/src/main/java/com/seb_main_004/whosbook/response/ErrorResponse.java
  server/src/main/java/com/seb_main_004/whosbook/stubdata/Stub.java
  server/src/main/java/com/seb_main_004/whosbook/vaildator/NotSpace.java
  server/src/main/java/com/seb_main_004/whosbook/vaildator/NotSpaceValidator.java
  server/src/main/resources/application.properties
Labels: BE

#25 공용컴포넌트 tailwindcss, styled-component 설정
  client/.eslintignore
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/components/buttons/Button.tsx
  client/src/components/input/Input.tsx
  client/src/components/label/Label.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/pages/MainPage.tsx
  client/src/styles/GlobalStyles.ts
  client/src/styles/theme.ts
  client/src/tailwind.config.js
  client/src/types/styled-components.d.ts
  client/tsconfig.json
  client/vite.config.ts
Labels: enhancement, Layout, FE

#35 [BE] exceptionCode 추가
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
Labels: BE, Exception

#36 Feat/be-curationPost 큐레이션 작성 기능 추가
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/utils/UriCreator.java
  server/src/main/resources/application.properties
Labels: BE

#37 [BE] Member도메인 Post기능 구현
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/repository/MemberRepository.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#39 feat: jwt로그인 및 자격검증 구현 완료
  server/build.gradle
  server/src/main/java/com/seb_main_004/whosbook/auth/dto/LoginDto.java
  server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/seb_main_004/whosbook/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/seb_main_004/whosbook/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/seb_main_004/whosbook/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/seb_main_004/whosbook/auth/utils/ErrorResponder.java
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
  server/src/main/java/com/seb_main_004/whosbook/stubdata/Stub.java
  server/src/main/resources/application.properties
Labels: BE

#40 Feat/be-curationModify 큐레이션 수정 기본 기능 구현 (회원 제외)
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#41 feat: CustomFilterConfigurer 메서드에 jwtVerificationFilter 추가
  server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
Labels: BE

#47 Feat/fe-curationCard 큐레이션 카드 컴포넌트 레이아웃 구현
  client/src/components/CurationCard.tsx
  client/src/components/SubCuratorCard.tsx
Labels: Layout, FE

#48 [BE] 멤버도메인 CRUD(인증기능 미포함)
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/repository/MemberRepository.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#45 feat: 큐레이션 작성 수정시 회원관련 기능 추가
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#50 큐레이션 수정 페이지 레이아웃 작업 완료
  client/src/components/quill/QuillEditor.tsx
  client/src/pages/CurationEditPage.tsx
  client/src/styles/GlobalStyles.ts
Labels: Layout, FE

#51 feat: 큐레이션 삭제 기능
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
Labels: BE

#53 Feat/fe-curationCard 큐레이션 카드 컴포넌트 레이아웃 수정
  client/src/components/CurationCard.tsx
  client/src/components/SubCuratorCard.tsx
Labels: enhancement, Layout, FE

#54 이미지 업로드 미리보기 기능 구현
  client/src/Routes.tsx
  client/src/components/imageUpload/ImageUpload.tsx
  client/src/components/input/Input.tsx
  client/src/components/label/Label.tsx
  client/src/img/duckling.jpg
  client/src/img/profile_img1.png
  client/src/img/profile_img2.png
  client/src/pages/ExamPage.tsx
  client/src/pages/MainPage.tsx
Labels: FE

#55 회원가입 페이지 레이아웃
  client/src/Routes.tsx
  client/src/components/.gitkeep
  client/src/components/imageUpload/ImageUpload.tsx
  client/src/components/input/Input.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignUp.tsx
  client/src/styles/theme.ts
Labels: Layout, FE

#57 마이페이지, 타유저페이지 공동 컴포넌트 레이아웃 구현
  client/package-lock.json
  client/src/Routes.tsx
  client/src/components/profile/ProfileDetail.tsx
  client/src/components/profile/ProfileInfo.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/UserPage.tsx
Labels: Layout, FE

#59 Feat/be member / 멤버CRUD 리팩토링(인증기능 포함)
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#66 로그인 페이지
  client/src/Routes.tsx
  client/src/components/imageUpload/ImageUpload.tsx
  client/src/img/duckling.jpg
  client/src/img/google.png
  client/src/img/kakaotalk_logo.png
  client/src/img/naver_logo.png
  client/src/img/whosebook_logo.png
  client/src/pages/User/SignIn.tsx
  client/src/pages/User/SignUp.tsx
  client/src/styles/GlobalStyles.ts
Labels: FE

#67 모달 컴포넌트 레이아웃 구현 완료
  client/src/components/cards/CurationCard.tsx
  client/src/components/cards/SubCuratorCard.tsx
  client/src/components/modals/Modal.tsx
  client/src/components/modals/SearchModal.tsx
  client/src/components/profiles/ProfileDetail.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/UserPage.tsx
Labels: Layout, FE

#68 공통 버튼 컴포넌트에 기본 버튼 스타일 추가
  client/src/components/buttons/Button.tsx
Labels: enhancement, FE

#69 feat: 큐레이션 단일 상세 조회 기능 구현
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/CuratorResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
Labels: BE

#71 [Client] 공통 버튼 컴포넌트에 detail 스타일 추가
  client/src/components/buttons/Button.tsx
Labels: Layout, FE

#72 [Client] 공통 버튼 컴포넌트에 category 스타일 추가
  client/src/components/buttons/Button.tsx
  client/src/styles/theme.ts
Labels: Layout, FE

#73 [Server] 댓글 도메인 리팩토링
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
  server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
  server/src/main/java/com/seb_main_004/whosbook/reply/mapper/ReplyMapper.java
  server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java
Labels: BE

#74 [Client] 큐레이션 단일 상세 조회 페이지 레이아웃 완료
  client/src/Routes.tsx
  client/src/components/buttons/Button.tsx
  client/src/components/curations/BookInfo.tsx
  client/src/components/curations/CurationCreatedDate.tsx
  client/src/components/curations/CurationDetailInfo.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/input/SelectBox.tsx
  client/src/components/replies/ReplyCreatedDate.tsx
  client/src/components/replies/ReplyProfileInfo.tsx
  client/src/img/book_example.jpeg
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
Labels: Layout, FE

#86 Router enum으로 관리
  client/src/Routes.tsx
  client/src/components/input/Input.tsx
Labels: enhancement, FE

#75 Feat: member도메인 리팩토링
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/dto/MultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberAndCurationResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#99 댓글 이슈사항 리팩토링
  server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
  server/src/main/java/com/seb_main_004/whosbook/reply/dto/ReplyPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
  server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java
Labels: BE

#100 모달 Reducer 추가
  client/src/components/cards/CurationCard.tsx
  client/src/components/modals/Modal.tsx
  client/src/components/modals/SearchModal.tsx
  client/src/components/profiles/ProfileDetail.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/type/index.ts
  client/src/store/modalSlice.ts
  client/src/store/store.ts
Labels: enhancement, FE

#101 Feat/be member도메인 리팩토링
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#102 책 검색 모달과 작성 , 편집 페이지 연결
  client/src/components/modals/Modal.tsx
  client/src/components/modals/SearchModal.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
Labels: enhancement, FE

#109 feat: 공통 에러 핸들러 추가
  server/src/main/java/com/seb_main_004/whosbook/advice/GlobalExceptionAdvice.java
Labels: BE

#110 fix: setAllowedMethod 에 OPTIONS 추가
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
Labels: BE

#112 jwt 로그인, 회원가입 로직
  client/package-lock.json
  client/package.json
  client/src/api/axios.ts
  client/src/api/userApi.ts
  client/src/components/buttons/Button.tsx
  client/src/components/input/Input.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/pages/User/SignUp.tsx
  client/src/store/counterSlice.ts
  client/src/store/store.ts
  client/src/store/userSlice.ts
  client/src/types/user.ts
  client/src/utils/validation.ts
Labels: FE

#116 Refator/be jwtlogin 프론트 요청사항
  server/build.gradle
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/seb_main_004/whosbook/auth/controller/HelloHomeController.java
  server/src/main/java/com/seb_main_004/whosbook/auth/dto/LoginResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/seb_main_004/whosbook/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
  server/src/main/resources/application.properties
  server/src/main/resources/templates/hello-oauth2.html
Labels: BE

#118 refactor:오리진 주소 추가
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
Labels: BE

#119 login 후 memberId, nickname 정보 저장
  client/src/App.tsx
  client/src/Routes.tsx
  client/src/components/gnb/GlobalNavigationBar.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/pages/User/SignUp.tsx
  client/src/store/userSlice.ts
Labels: FE

#121 Feat: BE 깃허브 액션을 활용한 CI CD 구축
  .github/workflows/gradle.yml
  server/appspec.yml
  server/deploy.sh
  server/src/main/resources/application-before.properties
  server/src/main/resources/application.yml
Labels: BE

#123 Header 구현
  client/src/App.tsx
  client/src/Routes.tsx
  client/src/api/userApi.ts
  client/src/components/header/DropdownMenu.tsx
  client/src/components/header/GlobalNavigationBar.tsx
  client/src/components/imageUpload/ImageUpload.tsx
  client/src/pages/ExamBestCuration.tsx
  client/src/pages/ExamNewCuration.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/pages/User/SignUp.tsx
  client/src/store/userSlice.ts
  client/src/styles/GlobalStyles.ts
Labels: FE

#125 fix:불필요한 파일 정리
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/seb_main_004/whosbook/auth/controller/HelloHomeController.java
  server/src/main/resources/templates/hello-oauth2.html
Labels: BE

#127 fix: 소셜로그인 응답바디 데이터 추가
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
Labels: BE

#128 fix:sucess핸들러 빠진부분 추가,host 변경
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
Labels: BE

#130 Feat: Member도메인 페이지네이션 리팩토링
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#131 fix:oauth핸들러 수정
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
Labels: BE

#132 회원가입, 마이페이지 수정에서 쓰이는 이미지 업로드 기능
  client/src/api/userApi.ts
  client/src/components/header/DropdownMenu.tsx
  client/src/components/header/GlobalNavigationBar.tsx
  client/src/components/imageUpload/ImageUpload.tsx
  client/src/components/modals/Modal.tsx
  client/src/pages/User/SignIn.tsx
  client/src/pages/User/SignUp.tsx
  client/src/store/modalSlice.ts
  client/src/utils/image.ts
  client/src/utils/validation.ts
Labels: FE

#133 [Client] 큐레이션 CRUD 기능 구현
  client/src/Routes.tsx
  client/src/components/curations/BookInfo.tsx
  client/src/components/curations/CurationCreatedDate.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/input/SelectBox.tsx
  client/src/components/quill/QuillEditor.tsx
  client/src/components/replies/ReplyProfileInfo.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
Labels: FE

#135 fix:데이터 저장 위치 변경(test용 PR입니다)
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
Labels: BE

#134 마이페이지, 타유저페이지 api 요청 연결 (수정 필요)
  client/package-lock.json
  client/package.json
  client/src/Routes.tsx
  client/src/api/profileApi.ts
  client/src/components/cards/CurationCard.tsx
  client/src/components/cards/SubCuratorCard.tsx
  client/src/components/modals/Modal.tsx
  client/src/components/profiles/ProfileDetail.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/User/MyPage.tsx
  client/src/pages/User/SignUp.tsx
  client/src/pages/User/UserPage.tsx
  client/src/pages/UserPage.tsx
  client/src/types/card.ts
  client/src/types/index.ts
  client/src/types/profile.ts
Labels: FE

#137 fix:yml파일에 리다이렉트 URI추가
  server/src/main/resources/application.yml
Labels: BE

#139 feat: 큐레이션 이미지 업로드 기능 구현
  server/build.gradle
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationImageResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/CurationImage.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/CurationSaveImage.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationImageRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationSaveImageRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationImageService.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/image/service/S3StorageService.java
  server/src/main/java/com/seb_main_004/whosbook/image/service/StorageService.java
  server/src/main/java/com/seb_main_004/whosbook/image/utils/ImageStorageUtils.java
  server/src/main/resources/application.yml
Labels: BE

#143 fix:cors설정
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
Labels: BE

#154 feat: 타 유저가 작성한 큐레이션 목록 조회 API
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
  server/src/main/java/com/seb_main_004/whosbook/subscribe/entity/Subscribe.java
  server/src/main/java/com/seb_main_004/whosbook/subscribe/service/SubscribeService.java
Labels: BE

#157 fix : 회원가입 응답 오류 해결
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/OtherMemberResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
Labels: BE

#162 feat: 큐레이션 이미지 업로드 유효성 검사 및 수정 기능
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationImageDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationSaveImageRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationImageService.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/image/service/S3StorageService.java
  server/src/main/java/com/seb_main_004/whosbook/image/service/StorageService.java
  server/src/main/java/com/seb_main_004/whosbook/image/utils/ImageStorageUtils.java
Labels: BE

#160 [Client] 큐레이션 공개/비공개 기능 구현
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
Labels: FE

#163 메인 페이지 배너, 섹션, 푸터 구현
  client/package-lock.json
  client/package.json
  client/public/favicon_white.ico
  client/src/api/mainPageApi.ts
  client/src/api/userApi.ts
  client/src/components/Footer/Footer.tsx
  client/src/components/cards/CurationCard.tsx
  client/src/components/cards/CuratorCard.tsx
  client/src/components/gnb/GlobalNavigationBar.tsx
  client/src/components/header/DropdownMenu.tsx
  client/src/components/header/GlobalNavigationBar.tsx
  client/src/components/slider/NextArrow.tsx
  client/src/components/slider/PrevArrow.tsx
  client/src/components/slider/SimpleSlider.tsx
  client/src/img/banner1.jpg
  client/src/img/banner2.jpg
  client/src/img/banner3.jpg
  client/src/img/banner4.jpg
  client/src/img/github_icon.png
  client/src/img/jeongjwon.png
  client/src/img/juyoung.png
  client/src/img/jy.png
  client/src/img/notion_icon.png
  client/src/img/wook0112.png
  client/src/img/yschoi.png
  client/src/img/yungju.png
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/pages/User/SignUp.tsx
  client/src/styles/GlobalStyles.ts
  client/src/types/main.ts
  client/src/types/user.ts
  client/src/utils/removeImgTags.ts
Labels: FE

#167 eslint 규칙 추가
  client/.eslintrc
  client/src/api/mainPageApi.ts
  client/src/api/userApi.ts
Labels: enhancement, FE

#169 eslint에서 typescript를 인식하지 못해 발생한 오류 해결
  client/.eslintrc
  client/src/components/header/GlobalNavigationBar.tsx
Labels: bug, enhancement, FE

#168 타회원 페이지 - 회원 정보 조회, 구독기능(수정), 작성한 큐레이션 조회
  client/src/api/profileApi.ts
  client/src/components/cards/CurationCard.tsx
  client/src/components/cards/CuratorCard.tsx
  client/src/components/cards/SubCuratorCard.tsx
  client/src/components/modals/Modal.tsx
  client/src/components/profiles/ProfileCard.tsx
  client/src/components/profiles/ProfileDetail.tsx
  client/src/components/profiles/ProfileForm.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/pages/User/MyPage.tsx
  client/src/pages/User/UserPage.tsx
  client/src/store/userSlice.ts
  client/src/types/card.ts
  client/src/types/profile.ts
Labels: enhancement, FE

#170 env 환경변수 import.meta.env를 하는 번거로움 없애도록 별도 파일로 설정
  client/src/api/axios.ts
  client/src/utils/envValiable.ts
Labels: enhancement, FE

#166 feat: 베스트 큐레이션 리스트 조회 API
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationListResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#172 중첩 라우팅 설정 및 큐레이션카드 오류 수정
  client/src/Routes.tsx
  client/src/api/profileApi.ts
  client/src/components/cards/CurationCard.tsx
  client/src/components/cards/SubCuratorCard.tsx
  client/src/components/filter/Filter.tsx
  client/src/components/profiles/CuratorList.tsx
  client/src/components/profiles/LikeList.tsx
  client/src/components/profiles/ProfileCard.tsx
  client/src/components/profiles/ProfileDetail.tsx
  client/src/components/profiles/ProfileForm.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/profiles/WrittenList.tsx
  client/src/pages/User/MyPage.tsx
  client/src/pages/User/UserPage.tsx
  client/src/store/nicknameSlice.ts
  client/src/store/store.ts
  client/src/types/card.ts
Labels: bug, FE

#173 feat: 좋아요한 큐레이션 목록 조회 API
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#174 refactor: Member 도메인 Curation List Response 리팩토링
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
Labels: BE

#176 feat: 카테고리 기능 구현
  server/src/main/java/com/seb_main_004/whosbook/curation/category/Category.java
  server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryAllPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryService.java
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationListResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
Labels: BE

#180 feat: isLiked 기능 구현
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#179 feat:댓글 조회 구현
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/seb_main_004/whosbook/reply/controller/ReplyController.java
  server/src/main/java/com/seb_main_004/whosbook/reply/mapper/ReplyMapper.java
  server/src/main/java/com/seb_main_004/whosbook/reply/service/ReplyService.java
Labels: BE

#182 feat: isSubscirbed 기능 구현
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#181 fix: 좋아요한 큐레이션 목록조회 API 수정
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: bug, BE

#183 Loading, Error handling
  client/package-lock.json
  client/package.json
  client/src/Routes.tsx
  client/src/api/axios.ts
  client/src/api/userApi.ts
  client/src/assets/404.png
  client/src/assets/500.png
  client/src/assets/banner1.png
  client/src/assets/banner2.png
  client/src/assets/banner3.png
  client/src/assets/banner4.png
  client/src/assets/banner5.png
  client/src/assets/banner6.png
  client/src/assets/book_example copy.jpeg
  client/src/assets/book_example.jpeg
  client/src/assets/github_icon.png
  client/src/assets/google.png
  client/src/assets/jeongjwon.png
  client/src/assets/juyoung.png
  client/src/assets/jy.png
  client/src/assets/kakaotalk_logo.png
  client/src/assets/kyungju.png
  client/src/assets/naver_logo.png
  client/src/assets/notion_icon.png
  client/src/assets/profile_img1.png
  client/src/assets/profile_img2.png
  client/src/assets/whosebook_logo.png
  client/src/assets/wook0112.png
  client/src/assets/yschoi.png
  client/src/components/Footer/Footer.tsx
  client/src/components/Loading/ClockLoading.tsx
  client/src/components/cards/CuratorCard.tsx
  client/src/components/error/FrontError.tsx
  client/src/components/error/ServerError.tsx
  client/src/components/header/GlobalNavigationBar.tsx
  client/src/components/input/Input.tsx
  client/src/components/slider/SimpleSlider.tsx
  client/src/img/banner1.jpg
  client/src/img/banner2.jpg
  client/src/img/banner3.jpg
  client/src/img/banner4.jpg
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/utils/envValiable.ts
  client/src/utils/importImgUrl.ts
  client/src/utils/typeGuard.ts
Labels: FE

#184 feat: 회원 프로필이미지 CRUD 기능
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#191 Fix: 단일 카테고리 등록 안되는 문제 해결
  server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/category/CategoryPostDto.java
Labels: BE

#195 feat: 이미지 확장자 대소문자 여부 상관없는 검증 기능
  server/src/main/java/com/seb_main_004/whosbook/image/utils/ImageStorageUtils.java
Labels: BE

#192 단일 상세 큐레이션 페이지에서 좋아요 및 구독하기 기능 구현 및 리팩토링
  client/src/api/profileApi.ts
  client/src/components/cards/CurationCard.tsx
  client/src/components/curations/CurationDetailInfo.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/profiles/CuratorList.tsx
  client/src/components/profiles/LikeList.tsx
  client/src/components/profiles/ProfileCard.tsx
  client/src/components/profiles/ProfileDetail.tsx
  client/src/components/profiles/ProfileForm.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/profiles/WrittenList.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/store/nicknameSlice.ts
  client/src/store/store.ts
  client/src/types/card.ts
Labels: FE

#197 feat: 회원가입 시 프로필 이미지 등록 API
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#199 feat: 큐레이션 작성시 책정보 저장 및 조회 기능 구현
  server/src/main/java/com/seb_main_004/whosbook/book/BookService.java
  server/src/main/java/com/seb_main_004/whosbook/book/entity/Book.java
  server/src/main/java/com/seb_main_004/whosbook/book/entity/BookCuration.java
  server/src/main/java/com/seb_main_004/whosbook/book/repository/BookCurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/book/repository/BookRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationSingleDetailResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#202 feat: 소셜 회원가입 API 구현 및 일반 회원가입 리팩토링
  server/src/main/java/com/seb_main_004/whosbook/auth/Oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/SocialMemberPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#203 feat: 뉴, 베스트 큐레이션 카테고리별 조회 기능
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#205 fix: 멤버에 연관된 큐레이션 리스트 조회관련 오류 픽스
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapperClass.java
Labels: BE

#208 feat: 책정보 수정 기능 구현
  server/src/main/java/com/seb_main_004/whosbook/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/seb_main_004/whosbook/book/BookService.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/service/CurationService.java
Labels: BE

#207 마이페이지 , 타유저페이지 - 목록 조회 시 오류 수정
  client/src/components/profiles/LikeList.tsx
  client/src/components/profiles/WrittenList.tsx
Labels: bug, FE

#210 구글 OAuth 작업 중
  client/package-lock.json
  client/package.json
  client/src/Routes.tsx
  client/src/api/OAuthGoogle.ts
  client/src/api/axios.ts
  client/src/api/mainPageApi.ts
  client/src/api/userApi.ts
  client/src/assets/banner.png
  client/src/assets/banner4.png
  client/src/assets/banner5.png
  client/src/assets/banner6.png
  client/src/assets/book_example copy.jpeg
  client/src/components/alert/sweetAlert.ts
  client/src/components/header/DropdownMenu.tsx
  client/src/components/header/GlobalNavigationBar.tsx
  client/src/components/input/Input.tsx
  client/src/main.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/pages/User/SignUp.tsx
  client/src/pages/error/FrontError.tsx
  client/src/pages/error/ServerError.tsx
  client/src/store/userSlice.ts
  client/src/types/envVariable.ts
  client/src/utils/importImgUrl.ts
Labels: FE

#211 fix: 마이페이지 소셜로그인 수정
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
Labels: BE

#220 fix: 소셜로그인
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
Labels: BE

#217 단일 상세 페이지 - 댓글 CRUD 기능 구현
  client/src/api/replyApi.ts
  client/src/components/curations/BookInfo.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/profiles/LikeList.tsx
  client/src/components/replies/ReplyProfileInfo.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/store/repliesSlice.ts
  client/src/store/store.ts
Labels: FE

#230 fix: 소셜 회원가입 프로필이미지 수정
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/SocialMemberPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapperClass.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#234 [Client] Best & New 큐레이션 리스트 페이지
  client/src/Routes.tsx
  client/src/api/axios.ts
  client/src/api/curationApi.ts
  client/src/components/buttons/Button.tsx
  client/src/components/cards/CurationCard.tsx
  client/src/components/category/CategoryTag.tsx
  client/src/components/input/SelectBox.tsx
  client/src/components/modals/SearchModal.tsx
  client/src/components/profiles/ProfileCard.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
  client/src/pages/ExamBestCuration.tsx
  client/src/pages/ExamNewCuration.tsx
  client/src/types/card.ts
  client/src/types/main.ts
Labels: FE

#235 [Client] Quill Editor에 이미지 업로드 시 URL로 반영
  .gitignore
  client/index.html
  client/src/components/quill/QuillEditor.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/styles/GlobalStyles.ts
Labels: bug, FE

#233 fix: 회원 프로필이미지 수정 기능
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#236 프로필 이미지 관련 수정
  client/src/components/cards/CurationCard.tsx
  client/src/components/cards/SubCuratorCard.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/profiles/ProfileCard.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/replies/ReplyProfileInfo.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
  client/src/store/repliesSlice.ts
  client/src/types/card.ts
Labels: bug, FE

#239 fix: 마이페이지 관 api 응답 수정
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationMultiResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/mapper/CurationMapper.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/OtherMemberResponseDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapperClass.java
Labels: BE

#240 feat: 베스트 큐레이터 리스트 조회 기능
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/BestCuratorDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapperClass.java
  server/src/main/java/com/seb_main_004/whosbook/member/repository/MemberRepository.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#241 fix: 구독 변수명 변경
  server/src/main/java/com/seb_main_004/whosbook/member/entity/Member.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapperClass.java
Labels: BE

#243 [Client] Best / New 큐레이션 리스트 + Category API 요청 기능 구현
  client/src/components/category/CategoryTag.tsx
  client/src/components/curations/CurationDetailInfo.tsx
  client/src/components/input/SelectBox.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
  client/src/store/categorySlice.ts
Labels: FE

#245 마이페이지, 타유저 페이지에서 목록 오류 수정
  client/src/pages/User/MyPage.tsx
  client/src/pages/User/UserPage.tsx
Labels: bug, FE

#247 fix: 마이페이지 프로필이미지 수정 오류
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/MemberPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#244 refactor: bestCurator 조회시 N+1 문제 해결을 위한 쿼리 개선
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
  server/src/main/java/com/seb_main_004/whosbook/member/dto/BestCuratorDto.java
  server/src/main/java/com/seb_main_004/whosbook/member/mapper/MemberMapperClass.java
  server/src/main/java/com/seb_main_004/whosbook/member/repository/MemberRepository.java
  server/src/main/java/com/seb_main_004/whosbook/member/service/MemberService.java
Labels: BE

#249 단일 상세 페이지에서 리팩토링
  client/src/components/curations/CurationDetailInfo.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
Labels: bug, FE

#251 #250 이전 페이지 정보 저장
  client/src/components/cards/MainCurationCard.tsx
  client/src/components/curations/CurationDetailInfo.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/User/SignIn.tsx
  client/src/styles/GlobalStyles.ts
  client/src/utils/image.ts
Labels: enhancement, FE

#252 마이페이지 오류 리팩토링
  client/src/components/profiles/CuratorList.tsx
  client/src/components/profiles/LikeList.tsx
  client/src/components/profiles/ProfileForm.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/profiles/WrittenList.tsx
Labels: bug, FE

#253 단일 큐레이션 상세페이지 및 편집 페이지 수정
  client/src/components/input/SelectBox.tsx
  client/src/components/modals/Modal.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/types/index.ts
Labels: bug, FE

#255 fix: 이모지 개수 유효성 검사
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
Labels: BE

#256 fix: 스프링 시큐리티 인가설정 및 토큰 만료 에러 응답 수정
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
  server/src/main/java/com/seb_main_004/whosbook/curation/controller/CurationController.java
  server/src/main/java/com/seb_main_004/whosbook/exception/ExceptionCode.java
  server/src/main/java/com/seb_main_004/whosbook/member/controller/MemberController.java
Labels: BE

#259 fix: 회원가입 인가설정 수정
  server/src/main/java/com/seb_main_004/whosbook/config/SecurityConfiguration.java
Labels: BE

#263 fix: 인가설정 수정
  server/src/main/java/com/seb_main_004/whosbook/auth/handler/MemberAuthenticationEntryPoint.java
Labels: BE

#266 fix:큐레이션 제목 유효성 검사
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
Labels: BE

#267 Refactor/fe user
  client/src/components/input/SelectBox.tsx
  client/src/components/modals/SearchModal.tsx
  client/src/pages/Curation/CurationEditPage.tsx
Labels: bug, enhancement, FE

#268 마이페지이지 리팩토링 - border 제거, 탈퇴 확인 모달
  client/src/components/modals/Modal.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/profiles/ProfileOut.tsx
  client/src/pages/User/MyPage.tsx
  client/src/types/index.ts
Labels: bug, FE

#269 메인페이지에서 로그아웃 후에도 글 작성 버튼이 보이는 버그 해결
  client/src/pages/MainPage.tsx
  client/src/store/userSlice.ts
Labels: bug, enhancement, FE

#270 [Client] Quill Editor 기능 추가 및 버그 수정
  client/index.html
  client/src/components/quill/QuillEditor.tsx
Labels: FE

#271 토큰 만료시 axios interceptor에서 조건문으로 분기타지 못하는 부분 코드 수정, 로그인 전에 글 작성 버튼 보이지 않도록 버그 수정
  client/src/api/axios.ts
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/pages/MainPage.tsx
Labels: bug, enhancement, FE

#272 [Client] Quill Editor 서버 주소 변경
  client/src/components/quill/QuillEditor.tsx
Labels: bug, FE

#275 마이페이지 추가 이슈 리팩토링
  client/src/components/profiles/CuratorList.tsx
  client/src/components/profiles/LikeList.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/profiles/ProfileOut.tsx
  client/src/components/profiles/WrittenList.tsx
  client/src/types/profile.ts
Labels: bug, FE

#278 프로필 이미지 리팩토링
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/profiles/ProfileInfo.tsx
Labels: bug, FE

#279 fix: 좋아요한 큐레이션 SQL ->JPQL 변경
  server/src/main/java/com/seb_main_004/whosbook/curation/repository/CurationRepository.java
Labels: BE

#280 pagination css 변경
  client/src/components/profiles/ProfileCard.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
Labels: bug, FE

#281 fix: 이모지 유효성 및 날짜 시간 한국시간 변경
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
  server/src/main/java/com/seb_main_004/whosbook/reply/entity/Reply.java
Labels: BE

#282 마이페이지 회원 수정 에러 리팩토링
  client/src/components/profiles/ProfileForm.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/pages/User/MyPage.tsx
Labels: bug, FE

#283 fix: 이모지 길이 확장
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPatchDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/dto/CurationPostDto.java
  server/src/main/java/com/seb_main_004/whosbook/curation/entity/Curation.java
Labels: BE

#285 fix: url, thumbnail 컬럼 정의 수정
  server/src/main/java/com/seb_main_004/whosbook/book/entity/Book.java
Labels: BE

#287 update readme.md
  README.md
Labels: Documentation

#286 전체 카테고리 버튼 리팩토링
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
Labels: FE

#288 Readme
  README.md
Labels: Documentation

#289 Readme
  README.md
Labels: Documentation

#290 Readme
  README.md
Labels: Documentation

#291 Readme
  README.md
Labels: Documentation

#292 Readme
  README.md
Labels: Documentation

#293 마이페이지 / BEST / NEW 큐레이션 페이지 - 페이지네이션 이슈에 따른 리팩토링
  client/src/Routes.tsx
  client/src/components/category/CategoryTag.tsx
  client/src/components/filter/Filter.tsx
  client/src/components/header/GlobalNavigationBar.tsx
  client/src/components/profiles/CuratorList.tsx
  client/src/components/profiles/LikeList.tsx
  client/src/components/profiles/WrittenList.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/MyPage.tsx
  client/src/pages/User/UserPage.tsx
Labels: bug, FE

#294 큐레이션 단일 상세페이지에서 뒤로가기 작동 시 undefined 수정
  client/src/components/cards/CurationCard.tsx
  client/src/components/slider/SimpleSlider.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
  client/src/pages/MainPage.tsx
  client/src/utils/validation.ts
Labels: bug, FE

#297 #296 큐레이션 수정 페이지 유효성 검증 적용
  client/src/components/input/SelectBox.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
Labels: bug, enhancement, FE

#300 이미지 업로드 버그 수정
  client/src/api/profileApi.ts
  client/src/api/userApi.ts
  client/src/components/header/GlobalNavigationBar.tsx
  client/src/components/imageUpload/ImageUpload.tsx
  client/src/components/profiles/ProfileForm.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/SignUp.tsx
  client/src/styles/GlobalStyles.ts
Labels: bug, enhancement, FE

#304 Footer 적용
  client/src/components/Footer/Footer.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/User/MyPage.tsx
  client/src/pages/User/UserPage.tsx
Labels: bug, enhancement, FE

#306 #302 마이페이지 내 컨텐츠 min-heigth 수정
  client/src/pages/User/MyPage.tsx
Labels: bug, enhancement, FE

#310 [Client] 큐레이션 단일 상세 조회 페이지 스타일 수정
  client/src/components/curations/CurationCreatedDate.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/components/replies/ReplyCreatedDate.tsx
  client/src/components/replies/ReplyProfileInfo.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
  client/src/pages/Curation/CurationWritePage.tsx
  client/src/styles/GlobalStyles.ts
Labels: Layout, FE

#312 Fix/react quill
  client/src/components/input/SelectBox.tsx
  client/src/pages/Curation/CurationDetailPage.tsx
  client/src/pages/Curation/CurationEditPage.tsx
Labels: bug, enhancement, FE

#315 fix: react-quill HTML태그들에서 모든 스타일 제거
  client/src/components/cards/CurationCard.tsx
  client/src/components/cards/MainCurationCard.tsx
  client/src/utils/removeImgTags.ts
Labels: bug, enhancement, FE

#317 Fix/unused variable
  client/src/utils/removeImgTags.ts
Labels: enhancement, FE

#318 마이페이지 페이지네이션 리팩토링
  client/src/Routes.tsx
  client/src/components/cards/CuratorCard.tsx
  client/src/components/cards/SubCuratorCard.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/filter/Filter.tsx
  client/src/components/profiles/CuratorList.tsx
  client/src/components/profiles/LikeList.tsx
  client/src/components/profiles/WrittenList.tsx
  client/src/components/replies/ReplyProfileInfo.tsx
  client/src/pages/User/MyPage.tsx
  client/src/pages/User/UserPage.tsx
  client/src/types/index.ts
Labels: bug, enhancement, FE

#323 fix: 회원탈퇴 시 알림 문구 변경, Sweet Alert 처리안된 부분 추가
  client/src/api/axios.ts
  client/src/api/userApi.ts
  client/src/components/alert/sweetAlert.ts
  client/src/components/curations/CurationDetailInfo.tsx
  client/src/components/curations/CurationProfileInfo.tsx
  client/src/components/profiles/ProfileInfo.tsx
  client/src/pages/Curation/BestCurationPage.tsx
  client/src/pages/Curation/NewCurationPage.tsx
  client/src/pages/User/SignIn.tsx
Labels: bug, enhancement, FE

#320 feat: Unhandled Exception 슬랙 연동
  server/build.gradle
  server/src/main/java/com/seb_main_004/whosbook/advice/ErrorSlackConnectTestController.java
  server/src/main/java/com/seb_main_004/whosbook/advice/GlobalExceptionAdvice.java
  server/src/main/resources/application.yml
Labels: BE

#325 Config: 깃헙 액션 CD를 위한 환경변수 설정
  .github/workflows/gradle.yml
Labels: BE

#326 fix: google login 버그 수정
  client/src/pages/User/SignIn.tsx
Labels: bug, enhancement, FE
